version: '3'

volumes:
  letsencrypt:
  certbot:

networks:
  vnet-nginx:

services:
  nginx:
    #image: nginx
    build: .
    container_name: nginx-01
    hostname: nginx-01
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/http.d:/etc/nginx/http.d # arquivo de configuração do site nginx
      - letsencrypt:/etc/letsencrypt # Certificado real
      - certbot:/var/www/certbot  # Desafio de validade/renovação do certificado
      #- ./data/certbot/var/lib/letsencrypt:/var/lib/letsencrypt # Certificado real
      #- ./data/letsencrypt:/etc/nginx/certs
    networks: 
      - vnet-nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    #image: certbot/certbot
    build: 
      context: .
      dockerfile: Dockerfile-certbot
    depends_on:
      - nginx
    container_name: certbot-01
    hostname: certbot-01
    # command: certonly --webroot --webroot-path=/var/www/certbot --email rafael.melo@softvision.com.br --agree-tos --no-eff-email --force-renewal -d vauter.simplificou.com # funciona um site por vez manual
    # command: --nginx -d vauter.simplificou.com --email rafael.melo@softvision.com.br --agree-tos --no-eff-email --force-renewal # configura todos sites automaticamente
    # command: certonly --staging --webroot --webroot-path=/var/www/certbot --email rafael.melo@softvision.com.br --agree-tos --no-eff-email --force-renewal -d app1.simplificou.com # somente para testes
    # command: --staging -d app1.simplificou.com -d app2.simplificou.com --email rafael.melo@softvision.com.br --agree-tos --no-eff-email --force-renewal # somente para testes
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # somente para testes
    # entrypoint: /bin/sh -c 'trap exit TERM; certbot certonly --webroot --webroot-path=/var/www/certbot --email rafael.melo@softvision.com.br --agree-tos --no-eff-email --force-renewal -d graficabluebox.com.softvision.com.br; while :; do certbot renew; sleep 60s; done;'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/nginx/http.d:/etc/nginx/http.d # arquivo de configuração do site nginx
      - letsencrypt:/etc/letsencrypt # Certificado real
      - certbot:/var/www/certbot  # Desafio de validade/renovação do certificado
    networks:
      - vnet-nginx