version: '3'

volumes:
  letsencrypt:
  certbot:

networks:
  vnet-nginx:

services:
  nginx:
    #image: nginx
    build: .
    container_name: nginx-01
    hostname: nginx-01
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/http.d:/etc/nginx/http.d # arquivo de configuração do site nginx
      - letsencrypt:/etc/letsencrypt # Certificado real
      - certbot:/var/www/certbot  # Desafio de validade/renovação do certificado
      #- ./data/certbot/var/lib/letsencrypt:/var/lib/letsencrypt # Certificado real
      #- ./data/letsencrypt:/etc/nginx/certs
    networks: 
      - vnet-nginx

  certbot:
    #image: certbot/certbot
    build: 
      context: .
      dockerfile: Dockerfile-certbot
    depends_on:
      - nginx
    container_name: certbot-01
    hostname: certbot-01
    command: certonly --webroot --webroot-path=/var/www/certbot --email uziel@simplificou.com --agree-tos --no-eff-email --force-renewal -d app1.simplificou.com # funciona um site por vez manual
    # command: -d app1.simplificou.com -d app2.simplificou.com --email uziel@simplificou.com --agree-tos --no-eff-email --force-renewal # configura todos sites automaticamente
    # command: certonly --staging --webroot --webroot-path=/var/www/certbot --email uziel@simplificou.com --agree-tos --no-eff-email --force-renewal -d app1.simplificou.com
    # command: --staging -d app1.simplificou.com -d app2.simplificou.com --email uziel@simplificou.com --agree-tos --no-eff-email --force-renewal
    volumes:
      - ./data/nginx/http.d:/etc/nginx/http.d # arquivo de configuração do site nginx
      - letsencrypt:/etc/letsencrypt # Certificado real
      - certbot:/var/www/certbot  # Desafio de validade/renovação do certificado
    networks:
      - vnet-nginx